routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'blog');

Auth::routes();

//Cliente
Route::get('blog',              'Web\PageController@blog')->name('blog');
Route::get('entrada/{slug}',    'Web\PageController@post')->name('post');
Route::get('categoria/{slug}',  'Web\PageController@category')->name('category');
Route::get('etiqueta/{slug}',   'Web\PageController@tag')->name('tag');

//Admin 
Route::resource('tags',         'Admin\TagController');
Route::resource('categories',   'Admin\CategoryController');
Route::resource('posts',        'Admin\PostController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name', 'slug','body'
    ];

   
    public function posts(){
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Http\Requests\CategoryStoreRequest;
use App\Http\Requests\CategoryUpdateRequest;

use App\Category;

class CategoryController extends Controller
{

    public function __construct(){
        //Proteccion basica
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('id', 'DESC')->paginate();

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryStoreRequest $request)
    {
        $category = Category::create($request->all());
        return redirect()->route('categories.edit', $category->id)->with('info', 'Categoria Creada con Exito!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);

        return view('admin.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);

        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateRequest $request, $id)
    {
        $Category = Category::find($id);

        $Category->fill($request->all())->save();
        return redirect()->route('categories.edit', $Category->id)->with('info', 'Categoria actualizada con Exito!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Category = Category::find($id)->delete();

        return back()->with('info', 'Eliminado correctamente');
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')
       <div class="container">
           <div class="row">
               <div class="col-md-8 col-md-offset-2">
                   <div class="card">
                       <div class="card-header">
                           Crear Etiqueta
                       <a href=" {{ route('categories.create')}}" class="btn btn-sm btn-primary float-right">Crear</a>
                       </div>
                       <div class="card-body">
                           {!! Form::open(['route' => 'categories.store']) !!}
                                @include('admin.categories.partials.form')
                           {!! Form::close() !!}
                       </div>
                   </div>
               </div>
           </div>
       </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
       <div class="container">
           <div class="row">
               <div class="col-md-8 col-md-offset-2">
                   <div class="card">
                       <div class="card-header">
                           Editar Categorias
                       <a href=" {{ route('categories.create')}}" class="btn btn-sm btn-primary float-right">Crear</a>
                       </div>
                       <div class="card-body">
                           {!! Form::model($category, ['route' => ['categories.update', $category->id], 
                                'method' => 'PUT']) !!}
                                @include('admin.categories.partials.form')
                           {!! Form::close() !!}
                       </div>
                   </div>
               </div>
           </div>
       </div>
@endsection

resources/views/admin/categories/index.blade.php
 @extends('layouts.app')

 @section('content')
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="card">
                        <div class="card-header">
                            Lista de Categorias
                        <a href=" {{ route('categories.create')}}" class="btn btn-sm btn-primary float-right">Crear</a>
                        </div>
                        <div class="card-body">
                            <table class="table table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th width="10px">ID</th>
                                        <th>Nombre</th>
                                        <th colspan="3">&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($categories as $category)
                                        <tr>
                                            <td>{{ $category->id }}</td>
                                            <td>{{ $category->name }}</td>
                                            <td width="10px"> 
                                                <a href="{{ route('categories.show', $category->id) }}" class="btn btn-small btn-primary">Ver</a>
                                            </td>
                                            <td width="10px"> 
                                                <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-small btn btn-success">Editar</a>
                                            </td>
                                            <td width="10px"> 
                                                {!! Form::open(['route' => ['categories.destroy', $category->id],
                                                    'method' => 'DELETE']) !!}

                                                    <button class="btn btn-sm btn-danger">Eliminar</button>

                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{ $categories->render() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
 @endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.app')

@section('content')
       <div class="container">
           <div class="row">
               <div class="col-md-8 col-md-offset-2">
                   <div class="card">
                       <div class="card-header">
                           Ver Categoria
                       <a href=" {{ route('tags.create')}}" class="btn btn-sm btn-primary float-right">Crear</a>
                       </div>
                       <div class="card-body">
                        <p><strong>Nombre</strong> {{ $category->name}}</p>
                        <p><strong>Slug</strong> {{ $category->slug}}</p>
                        <p><strong>Contenido</strong> {{ $category->body}}</p>

                       </div>
                   </div>
               </div>
           </div>
       </div>
@endsection